version: "3"
services:
  web:
    image: alphazero/typegraphql_example:1
    ports:
      - "4000:4000"
    environment:
      DATABASE_PASSWORD: ""
    depends_on:
      - db
    build: .
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: postgres
      POSTGRES_DB: typegraphql_example
    restart: always
    expose:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgres/data
volumes:
  pgdata:
